"""Add the field in the DB of the Email

Revision ID: 3186532a680d
Revises: ae476a3553e9
Create Date: 2026-04-07 00:19:41.090550

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3186532a680d'
down_revision: Union[str, Sequence[str], None] = 'ae476a3553e9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('user_email', sa.String(), nullable=True))
    op.drop_column('users', 'email')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('email', sa.VARCHAR(), autoincrement=False, nullable=True))
    op.drop_column('users', 'user_email')
    # ### end Alembic commands ###
